spring:
  datasource: #数据源
    url: jdbc:mysql://188.131.143.167:3306/house?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC 
    username: house_dev
    password: mysql@2020
    driverClassName: com.mysql.cj.jdbc.Driver
logging:
  level:
    root: info
    com.springbootDemo: debug
    com.springbootDemo.*.dao: debug
mybatis:
  #config-locations: mybatis/mybatis-config.xml
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.house.**.entity